import reflex as rx

from HUST_Student.components.ui import theme as T
from HUST_Student.states.folder_state import FolderState


def essay_section():
    return rx.vstack(
        rx.hstack(
            rx.text(
                rx.cond(FolderState.answer_language == "Foreign", "Native", "Foreign"),
                font_size="0.8rem",
                font_weight="700",
                color=T.TEXT_MUTED,
                text_transform="uppercase",
                letter_spacing="0.08em",
            ),
            rx.spacer(),
            rx.text(
                FolderState.current_test_index + 1,
                " / ",
                FolderState.test_question_count,
                font_weight="700",
                color=T.TEXT_SECONDARY,
                font_size="0.9rem",
            ),
            width="100%",
            align="center",
        ),
        rx.progress(
            value=rx.cond(
                FolderState.test_question_count > 0,
                ((FolderState.current_test_index + 1) * 100) // FolderState.test_question_count,
                0,
            ),
            max=100,
            width="100%",
            color_scheme="blue",
            size="2",
        ),
        rx.box(
            rx.text(
                FolderState.current_question_display,
                font_size="1.35rem",
                font_weight="700",
                color=T.TEXT_PRIMARY,
                text_align="left",
            ),
            padding="1.25rem",
            border=f"1px solid {T.BORDER}",
            border_radius=T.RADIUS_LG,
            bg=T.SURFACE,
            width="100%",
            min_height="100px",
            box_shadow=T.SHADOW_CARD,
        ),
        rx.box(
            rx.text("Đáp án của bạn", font_weight="600", color=T.TEXT_SECONDARY),
            rx.input(
                value=FolderState.written_answer,
                on_change=FolderState.set_written_answer,
                placeholder="Nhập đáp án",
                width="100%",
                height="140px",
                bg=T.BORDER_LIGHT,
                border=f"1px solid {T.BORDER}",
                border_radius=T.RADIUS_LG,
                padding="1.25rem",
                font_size="1rem",
                color=T.TEXT_PRIMARY,
                _focus={"border_color": T.PRIMARY, "box_shadow": f"0 0 0 3px {T.PRIMARY_LIGHT}"},
            ),
            spacing="3",
            width="100%",
        ),
        rx.cond(
            FolderState.check_feedback != "",
            rx.text(
                FolderState.check_feedback,
                font_size="0.9rem",
                color=rx.cond(FolderState.check_feedback.contains("✅"), T.SUCCESS, T.DANGER),
                font_weight="500",
                text_align="center",
            ),
            rx.box(),
        ),
        rx.hstack(
            rx.button(
                "Đóng",
                on_click=FolderState.close_test,
                bg=T.BORDER_LIGHT,
                color=T.TEXT_PRIMARY,
                border_radius=T.RADIUS_MD,
                padding="0.6rem 1.2rem",
                font_weight="600",
                _hover={"bg": T.BORDER},
            ),
            rx.button(
                "Kiểm tra",
                on_click=FolderState.check_current_answer,
                bg=T.WARN,
                color="white",
                border_radius=T.RADIUS_MD,
                padding="0.6rem 1.2rem",
                font_weight="700",
                _hover={"filter": "brightness(0.95)"},
            ),
            rx.spacer(),
            rx.button(
                "Tiếp",
                on_click=FolderState.next_test_question,
                bg=rx.cond(FolderState.written_answer != "", T.PRIMARY, T.PRIMARY_DISABLED),
                color="white",
                font_weight="700",
                border_radius=T.RADIUS_MD,
                padding="0.6rem 1.2rem",
                cursor=rx.cond(FolderState.written_answer != "", "pointer", "not-allowed"),
                _hover={"bg": T.PRIMARY_HOVER},
            ),
            width="100%",
            align="center",
            spacing="3",
        ),
        spacing="4",
        width="100%",
    )
